version: "3.7"
services:
  mongo-service:
    image: mongo
    container_name: hhovhann-mongo
    volumes:
      - db-data:/data/db
      - db-data:/data/configdb
    networks:
      - backend
    ports:
      - "27017:27017"
    restart: always

  web-service:
    # replace username/repo:tag with your name and image details
    image: hhovhann/spring-boot-docker:latest
    container_name: hhovhann-webapp
    build:
      context: .
      args:
        JAR_FILE: ${JAR_FILE}
    ports:
      - "8080:8080"
    working_dir: /app
    networks:
      - backend
    links:
      - mongo-service
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
#    configs:
#      - APPLICATION_PROPERTIES_FILE
#
#configs:
#  APPLICATION_PROPERTIES_FILE:
#    file: ${APPLICATION_PROPERTIES_FILE}

# Networks to be created to facilitate communication between containers
networks:
  backend:

# Volumes
volumes:
  db-data:
