version: "3.7"
services:
  hhovhann-mongo-service:
    image: mongo
    container_name: hhovhann-mongo-service
    volumes:
      - db-data:/data/db
      - db-data:/data/configdb
    networks:
      - backend
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/ff4j || --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  hhovhann-web-service:
    # replace username/repo:tag with your name and image details
    image: hhovhann/spring-boot-docker:latest
    container_name: hhovhann-web-service
    build:
      context: .
      args:
        JAR_FILE: ${JAR_FILE}
        APPLICATION_PROPERTIES_FILE: ${APPLICATION_PROPERTIES_FILE}
        META_RING_CONFIGURATION_FILE: ${META_RING_CONFIGURATION_FILE}
    ports:
      - "8080:8080"
    working_dir: /usr/src/app
    volumes:
      - web-data:/usr/src/app
    networks:
      - backend
    depends_on:
      - hhovhann-mongo-service
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    secrets:
      # This will keep application.properties file under run/secrets/APPLICATION_PROPERTIES_FILE
      - APPLICATION_PROPERTIES_FILE

secrets:
  APPLICATION_PROPERTIES_FILE:
    file: ${APPLICATION_PROPERTIES_FILE}
# Networks to be created to facilitate communication between containers
networks:
  backend:

# Volumes
volumes:
  db-data:
  web-data:
